### ISSUE TITLE
Use ECC by default in the tools app

### ISSUE THREAD

**Issue by Kharya1337** [PeculiarVentures/fortify-tools#189] opened 2024-08-21 09:38 UTC
> We should also update to using ECC by default in the tools app

![image](https://github.com/user-attachments/assets/f299117a-26e0-4150-b446-ff8c8d7a3e25)

**Comment by OleksandrSPV** [comment] 2024-09-02 12:42
Duplicate of #197 
@Kharya1337 Sorry, I missed and created another

**Closed by OleksandrSPV** 2024-09-02 12:42 UTC
